### ISSUE TITLE
Exception in fiber prints stack trace twice

### ISSUE THREAD

**Issue by mikehearn** [puniverse/quasar#156]
If I throw an exception from inside a fiber, there is an issue with redundant logging. I expect the framework to just surface the exception by rethrowing it at the point where I started or resumed this fiber, which it does, but it also runs the Fiber.defaultExceptionHandler ... twice. This results in stderr spam. I'd rather it printed nothing at all and let the exception propagate out of the fiber like any other.

**Comment by pron** [comment]
A Fiber is both a thread (in the abstract sense) and a `j.u.c.Future`. As a `Future`, it is required to throw any exceptions when it is joined (`Future.get`), and as a thread it is required to log any uncaught exception, as it may never be joined. But precisely for that reason we have `Fiber.setDefaultUncaughtExceptionHandler`/`Fiber.setUncaughtExceptionHandler`, so that you can turn this behavior off.

If the exception handler is called twice, that is, indeed, a bug, and we'll look into that.

**Comment by pron** [comment]
Should be fixed now (i.e. exception should only be printed once). You can get the new version from the `0.7.0` branch or `0.7.5-SNAPSHOT` on Sonatype.
