### ISSUE TITLE
Register! Actor - Request Helper to set ConcurrentHashMapV8() initial capacity

### ISSUE THREAD

**Issue by TonyLo1** [puniverse/quasar#166]
When building large actor networks the performance of register! Actor (Clojure API) degrades rapidly when large numbers of actors are registered (Several hundred thousand). The ability to set the initial capacity (to a custom value, e.g. 2,000,000) of the ConcurrentHashMapV8() used for the actor registry should improve this.

**Comment by pron** [comment]
May I ask why you'd want to register so many actors? Registration is meant to a discovery service for bootstrapping only. If you need a hash-map of actors, each service registers one actor that's responsible for discovery for that particular service, and that actor supplies the mapping. 

The reason your solution is problematic is because registration interacts with Quasar clustering, where the effects of using registration directly as a large-scale discovery service would be much worse. In general, registry is global: not only global for a JVM, but for an entire cluster. If you're running multiple components, each would pollute this global namespace with a lot of global symbols. If you want to register more than a few actors for each application/component, you should probably rethink your design.

**Comment by TonyLo1** [comment]
Ok, thanks this was useful feedback. I understand the intent of the registration service more clearly now, i.e. it's for service discovery. We do plan on several million actors distributed across a cluster. If using register! for this is problematic as you say, then we need to maintain our own distributed actor table. We will have to essentially duplicate the functionality of register and maintain a node address and actor ref for each actor. You can image our requirement as similar to a graph DB where each actor is a node in the graph (with relatively complex internal data structure). We were hoping for an equivalent capability to Microsoft's GraphEngine (without the restrictions on node data types).

**Comment by pron** [comment]
Galaxy, the IMDG powering clustered Quasar can do all that, but it will be another few months until it is usable in production.

**Comment by TonyLo1** [comment]
Ok, cool - we will work with a single node for now in that case. Thx
