### ISSUE TITLE
Inherit @Suspendable and throws SuspendException

### ISSUE THREAD

**Issue by candrews** [puniverse/quasar#206]
It would be great if the instrumentation could consider inherited  `@Suspendable` annotations and examine the inheritance hierarchy to determine if any extended method definitions include `throws SuspendException`. Such a change would make code using Quasar a lot readable (as it wouldn't have to have `throws SuspendException` or `@Suspendable` everywhere) and less error prone (if a superclass or implemented interface should be instrumented, it's more or less guaranteed than all implementations should be too).

For example, it would be great for Quasar to instrument B.run in this example:
```java
public class B implements co.paralleluniverse.strands.SuspendableRunnable {
    public void run() {
        System.out.println("hello!");
    }
}
```
Analysis should be able to see that `run()` is an implementation of `co.paralleluniverse.strands.SuspendableRunnable.run()` which throws `SuspendException` and therefore know to instrument.

Similarly, D.run should be instrumented in this example:
```java
public abstract class C implements java.lang.Runnable {
    @Suspendable
    public abstract void run();
}

public class D extends C {
    @Override
    public void run(){
        System.out.println("hello!");
    }
}
```
Analysis should be able to see that `C.run()` is an implementation of `B.run()` which has `@Suspendable` and therefore know to instrument.

I've updated one of the Quasar tests to demonstrate this request for improvement (the tests I've added fail, of course): https://github.com/candrews/quasar/blob/inherit/quasar-core/src/test/java/co/paralleluniverse/fibers/instrument/SuspendableAnnotationTest.java

**Comment by circlespainter** [comment]
Thanks for the proposal but I have some reservations: first of all this is not a comprehensive solution because it doesn't eliminate annotations. Then:

> Such a change would make code using Quasar a lot readable (as it wouldn't have to have `throws SuspendException` or `@Suspendable` everywhere) and less error prone

I actually think the opposite is true, i.e. readability and maintainability are better now.

As for maintainability: at present we lack fully automatic, efficient instrumentation (which I think is the real solution and starting with JDK9+ there most likely _will_ be) so `SuspendExecution` is very much intentionally a _checked_ exception that puts `javac`'s capabilities to good use for the purpose of statically detecting suspendable methods, so ideally it should be used as much as possible (when potentially suspending, I mean).
Other suspendable-marking tools like `@Suspendable` are a second choice but they're needed in some cases.

I also think that this would _not_ benefit readability: first of all it would change a very clear local "anything that might suspend" marking policy into a less clear non-local "anything that might suspend, except if super is already marked" one.
Second, the information of what Quasar instrumentation will do with one's code not only would not be local to the code itself anymore, but not even necessarily in control: think about overriding from a library.
You could also lose control about efficiency, as instrumentation introduces some (very small, but this is relative the use case so taking away freedom is not a good idea) overhead: consider that some calls like reflection or accessors need to be instrumented in methods marked as suspendable because there's no way of telling statically if they'll suspend or not.

> if a superclass or implemented interface should be instrumented, it's more or less guaranteed than all implementations should be too

Why is that? Marking an overridden/abstract/interface method as suspendable just tells that it _might_ appear in a suspending stack (which BTW transitively carries over also to concrete non-overridden methods that call suspendable overridden/abstract/interface ones). One could perfectly meaningfully override a suspendable method with an implementation that doesn't suspend at all (like you did) and there's no point in instrumenting it: just the calls to its "super" need to be, in case some overrides do indeed suspend (and those specific overrides that suspend need to be instrumented too, of course).

If there's no point in instrumenting a method, why should Quasar's instrumentor waste resources on it and, again, perhaps even reducing its efficiency by instrumenting things that will never suspend anyway? This would also make the instrumentation phase slower and its efficiency is always taken into consideration as we don't want to inflate class loading times without a good reason.

Maybe we can also hear from @pron what he thinks.

**Comment by pron** [comment]
I agree with @circlespainter.
