### ISSUE TITLE
Problems with Strand.park (minimal example) (jdk1.8.0_121, quasar-0.7.7)

### ISSUE THREAD

**Issue by fab1an** [puniverse/quasar#255]
The following minimal snippet produces the uninstrumented warning at `Strand.park`:

```java
public static void main(String[] args) throws InterruptedException, ExecutionException, TimeoutException {
    
    new Fiber<>(() -> Channels.newIntChannel(1).receive())
       .start()
       .join(1, TimeUnit.SECONDS);
}
```

**Comment by fab1an** [comment]
Okay, this just came up with `0.7.7`, when using `0.7.6` there is no warning.

**Comment by pron** [comment]
0.7.7 introduced some problems in `verifyInstrumentation` that were hopefully addressed in 0.7.8. Can you try `0.7.8-SNAPSHOT`?

**Comment by jasons2000** [comment]
do you have an ETA for 0.7.8 ?

------ Original Message ------

**Comment by fab1an** [comment]
I tried `0.7.8-SNAPSHOT` two days ago. It still gives an error, but on another line.

**Comment by circlespainter** [comment]
The problem seems to be [here](https://github.com/puniverse/quasar/blob/0.7.0/quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/SuspendableHelper.java#L108), the call site is `IntChannel::receive` (as in the bytecode) while the callee according to `ExtendedStackTraceElement` (hotspot-optimized) is `QueueChannel::receive`. Neither is assignable to the other one but the `receive` method is declared in the common ancestor `ReceivePort`.

A fix should probably check that the relevant method  (`.receive()Ljava/lang/Object;` in this case) is declared in a common ancestor.
